### ISSUE TITLE
Can't Tab Through Page

### ISSUE THREAD

**Issue by jlind** [PowerKiKi/ie_expand_select_width#1]
I'm building off portions of your code to pull off the same idea in MooTools and I noticed a problem.
Users can't tab through the inputs on the page and actually get through the page.  Because they are on a select that's put at the bottom of the body when they tab next they are put back at the top of the page.

You should be able to listen for tabs in the cloned select and do some magic.  I'm still figuring that part out.

**Comment by PowerKiKi** [comment]
Correct. Keyboard support is limited indeed. I also believe it should be
somewhat possible to workaround that, but didn't have muche more time to
put into that.

But I'll gladly merge your commit if you come up with a solution.

**Comment by jlind** [comment]
After smashing my head against a wall for several hours I found it could be achieved with the "tabIndex" attribute, but I'd have to dynamically add the attribute to all desired tab-able elements for it to work for me.

After a browser uses something with "tabIndex" it returns to the top of the page, and ignores anything later without "tabIndex"

**Comment by jlind** [comment]
The best option I could come up with, and the way I ultimately went, was putting the cloned SELECT after the original, positioned absolutely. If a user is tabbing through it acts exactly as desired. If a user attempts to tab backwards (shift+tab) they get stuck. Since they tab back to the original it forces them forward onto the clone. I figure that's better than just completely destroying all tabbing.

**Comment by PowerKiKi** [comment]
By placing the clone right after the original, you will potentially break
the layout, won't you ?

The non-layout-breaking thing was my top priority so I am not sure I would
follow your approach in this case...

**Comment by jlind** [comment]
By using javascript to absolute position the element it didn't break in the one use case that I actually needed it for.
I haven't run into any issues (with IE8, recently) where an absolute positioned element breaks a layout.

**Comment by PowerKiKi** [comment]
Sounds interesting. Did you also try with the use-case found on the
webpage (http://powerkiki.github.com/ie_expand_select_width or in
your local clone) ?

Did you publish your version somewhere yet ?

**Comment by PowerKiKi** [comment]
While interesting I don't think I'll invest much more time in that plugin (die IE8 !). So I'll close this issue.
