### ISSUE TITLE
Problem with css outline-style:none

### ISSUE THREAD

**Issue by quedicesebas** [PowerKiKi/ie_expand_select_width#3]
I had this on my css:

![image](https://f.cloud.github.com/assets/1771574/897584/49fa286e-faf5-11e2-9c00-e294d1e59316.png)

when I move the mouse over any select, in IE8 there was a js error:
Unespecified error. at line 171, in method getComputedStyleMap:

![image](https://f.cloud.github.com/assets/1771574/897546/96a479cc-faf4-11e2-87e5-1c31c18605c5.png)

I found (looking at style array) that there are some css attributes with value as 'Unespecified error.', so thta's the problem! But the attributes was not in my css (outlineWidth and outline)

I found (looking at css in developer tools of IE8) that is because IE8 generates other properties, so select css properties look like this in the inspector:
![css](https://f.cloud.github.com/assets/1771574/897560/e61489d4-faf4-11e2-89f4-900f99d2e0d3.png)

I remove outline-style:none from my css and that resolve it, but I think that is a bug. You should change taht method.

**Comment by PowerKiKi** [comment]
That took a while, but it's now fixed. Now all unsupported CSS properties are simply ignored when cloning elements.

Also see http://stackoverflow.com/questions/12568549/ie-8-outline-width-unspecified-error
