### ISSUE TITLE
Expanded selects are "sticky"

### ISSUE THREAD

**Issue by nina-bee** [PowerKiKi/ie_expand_select_width#4]
I am using IE8 with this plugin and am experiencing a problem. It seems that intermittently, once the select box is expanded, it will stay open and expanded when mouseing off the select box. It's almost as if it does not detect the mouseout event - intermittently. I can make this happen sometimes on the demo site in the example using tables, which is how I am implementing. Any suggestions for a fix for this?

**Comment by PowerKiKi** [comment]
From my tests it would seems that the select stay expanded (the clone is never destroyed) if we open the select and choose the same option which was already selected. In that case, there is no `changed` event, so we don't know that our clone should be destroyed.

Unfortunately my IE8 is crashing _very_ frequently and I won't be able to spend too much time on that in the next few days. But I would gladly accept PR. I guess we should somehow detect when an option is selected, even if it is the same as before... that should probably be around there https://github.com/PowerKiKi/ie_expand_select_width/blob/gh-pages/javascripts/ie_expand_select_width.js#L65
